version: "3"
services:
  consul-server1:
    image: consul:1.14.3
    container_name: lqy-consul1
    restart: always
    volumes:
    - ./data:/consul/data:rw
    command: agent -server -client=0.0.0.0 -bootstrap-expect=2 -node=consul1
  consul-server2:
    image: consul:1.14.3
    container_name: lqy-consu2
    restart: always
    volumes:
    - ./data:/consul/data:rw
    command: agent -server -client=0.0.0.0 -retry-join=consul1 -node=consul2
  consul-client:
    image: consul:latest
    container_name: lqy-consu3
    restart: always
    ports:
      - 8500:8500
    command: agent -client=0.0.0.0 -retry-join=consul1 -ui -node=client1
networks:
  consul:
    driver: bridge