version: '3'
services:
  consul-server-1:
    image: consul:1.14.3
    restart: always
    ports:
      - "8500:8500"
    volumes:
      - ./data:/consul/data:rw
    command: agent -server -bootstrap-expect=3 -ui -client=0.0.0.0

  consul-server-2:
    image: consul:1.14.3
    restart: always
    ports:
      - "8501:8500"
    volumes:
      - ./data:/consul/data:rw
    command: agent -server -join=consul-server-1 -ui -client=0.0.0.0

  consul-server-3:
    image: consul:1.14.3
    restart: always
    ports:
      - "8502:8500"
    volumes:
      - ./data:/consul/data:rw
    command: agent -server -join=consul-server-1 -ui -client=0.0.0.0

  consul-client:
    image: consul:1.14.3
    restart: always
    ports:
      - "8600:8600/udp"
    volumes:
      - ./data:/consul/data:rw
    command: agent -join=consul-server-1 -ui -client=0.0.0.0
networks:
  consul:
    driver: bridge