version: "3"
services:
  consul:
    image: consul:1.14.3
    container_name: lqy-consul
    restart: always
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8600:8600"
    volumes:
    - ./data:/consul/data
    command: agent -server -bind=0.0.0.0 -client=0.0.0.0 -node=consul -bootstrap-expect=1 -ui
    
networks:
  default:
    external:
      name: lqy-network